feat(quickopen): Add binds to open in splits to Quick Open
onivim/oni2 pull request #3733
Opened 2021-07-03 10:27 UTC by CrossR

A rough first pass, but adds default bindings for selecting items from the quick open to open in current/vertical/horizontal/new tab.

Biinds aren't finalised, so some input there would be nice (Ctrl-s and Ctrl-v are the defaults in Fzf in vim which is why I went with them).

2021-07-06 00:50 UTC, bryphe commented on src/Model/GlobalCommands.re
> +    );
Awesome! Thanks for adding these 🎉

2021-07-06 00:54 UTC, bryphe commented on src/Model/State.re
> +      ),
The only concern I have here is that the `Control+V` keybinding would conflict with paste on Windows/Linux (ie, regressing https://github.com/onivim/oni2/issues/2308)

A couple ideas:
- We could use `Control+Shift+V` for opening in vertical tab
- We could use the `Shift+CR` keybinding for vertical, and `Control+T` for new tab

2021-07-06 00:55 UTC, bryphe commented on src/Model/GlobalCommands.re
> +        direction: Oni_Core.SplitDirection.NewTab,
Looks like this will address #2232 🎉

2021-07-06 00:55 UTC, bryphe requested changes
Thanks for taking this on, @CrossR ! Approach looks great to me. Just had a comment about the `Control+V` binding -

2021-07-06 00:56 UTC, bryphe commented on src/Model/State.re
> +      ),
This also conflicts with the `save` keybinding, but I think this one is OK - understandable that save wouldn't occur when the quickmenu is up.

2021-07-08 21:45 UTC, CrossR commented
Did a quick survey of some common binds for this sort of thing and updated them accordingly, but with Shift-enter as vertical open by default since we use c-v as copy.

That said, obviously if a user wanted to swap they could just do something like:

```json
  { "key": "<C-s>", "command": "list.selectHorizontal", "when": "listFocus" }
```

The only other thing I wanted to check here is if the command names are okay. VSCode has no equivalent, so wasn't sure if they should be prefaced with `oni` or something.

2021-07-08 23:37 UTC, bryphe commented
> Did a quick survey of some common binds for this sort of thing and updated them accordingly, but with Shift-enter as vertical open by default since we use c-v as copy.

Awesome! Thanks for looking into this @CrossR . Looks good to me.

> The only other thing I wanted to check here is if the command names are okay. VSCode has no equivalent, so wasn't sure if they should be prefaced with oni or something.

Hmm, good point - VSCode does have a `list.*` set of commands, so prefixing it with `oni.` will make it clear these are Onivim-specific, and keep us safe if VSCode does introduce keybindings with the same name.

2021-07-08 23:37 UTC, bryphe approved these changes

2021-07-09 22:59 UTC, CrossR commented
Swapped the names, added some basic docs, just waiting for the CI to be happy then I'll squash/merge.

2021-07-10 11:54 UTC, CrossR commented
/azp run

2021-07-12 20:13 UTC, bryphe commented
Sorry about the build issues; the CentOS build failure looks unrelated. I'll override and merge. 

Thanks for the awesome contribution @CrossR !

2021-07-12 20:14 UTC, merged